-- 성지덕 팀 허브 · Supabase 스키마
-- Supabase 프로젝트 > SQL Editor 에 붙여넣고 실행하세요.
create table if not exists troubleshooting (
  id          bigint generated by default as identity primary key,
  title       text not null,
  area        text,            -- '공통' | 'A' | 'B' | 'C'
  symptom     text,
  cause       text,
  solution    text,
  author      text,
  created_at  timestamptz default now()
);

alter table troubleshooting enable row level security;
-- MVP: 팀 내부 공유용 오픈 정책 (운영 전 반드시 조이기)
create policy "read all"   on troubleshooting for select using (true);
create policy "insert all" on troubleshooting for insert with check (true);
create policy "delete all" on troubleshooting for delete using (true);
